package pluginbridge

// Code generated by misaka-tools. DO NOT EDIT.
import (
	pluginsloader "misakadb/plugins/pluginsLoader"
"misakadb/clilog"
	plugin_0 "misakadb/base_unloader"
)

func RegisterBuiltinPlugins() {
clilog.Info("Load The All Plugins...")
	pluginsloader.RegisterBuiltinPlugin("misaka basic mode @misaka", plugin_0.Register)
}
