package pluginbridge

// Code generated by misaka-tools. DO NOT EDIT.
import (
	"misakadb/clilog"
	plugin_0 "misakadb/coin"
	pluginsloader "misakadb/plugins/pluginsLoader"
)

func RegisterBuiltinPlugins() {
	clilog.Info("Load The All Plugins...")
	pluginsloader.RegisterBuiltinPlugin("misaka basic mode on v0.1.9@misaka", plugin_0.Register)
}
